### ISSUE TITLE
Problem encoding multilingual strings containing Cyrillic letters

### ISSUE THREAD

**Issue by regdomain** [yas78/QRCodeLibVBA#4]
Hello
I need to encode a string that contains mixed symbols including Latin, Cyrillic letters, digits, and special characters. 
I faced some problem encoding multilingual strings containing Cyrillic letters. If a string starts with a Cyrillic letter the QR code is generated correctly. Also if up to 6 first symbols are non-Cyrillic there's no problem encoding the whole string. However if more than 6 first symbols are non-Cyrillic the subsequent Cyrillic letters are no longer encoded correctly, each being represented with double byte characters and the question marks. 
Do you have any clues on the issue?
Thank you for you work, the tool is very handy and easily portable between the Office programs.

**Comment by yas78** [comment]
問題が発生する文字列を提示していただくことは可能でしょうか？
エンコード前の文字列と、エンコード後の期待する文字列を提示していただければ調査可能かと思います。
私は文字セットShift_JISとUTF-8に対応したQRコードリーダーを所持していますが、その他の文字セットについては対応出来ないかもしれません。
出来る限り期待に添えるように対応しようと思いますので詳細な情報の提示をお願いします。

**Comment by regdomain** [comment]
Actually it is about payment QR codes adopted in Russia as a National Standard. This is the link for your reference (in Russian): https://docs.cntd.ru/document/1200110981 

Below is a dummy string to be encoded. It contains a few fields separated by a pipe symbol (|). Some fields contain Latin letters, the others are in Russian.

The string before QR code encoding:
ST00012|Name=ООО "Рога и копыта"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=АО "БАНК"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=Оплата заказа №123|Sum=100000

The string after QR code decoding:
ST00012|Name=�O�O�O "�Q���s�p �y �{���������p"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=�@�O "�A�@�N�K"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=�O���|�p���p �x�p�{�p�x�p ��123|Sum=100000

As you can see it is damaged so that Cyrillic letters are not displayed correctly. 

I investigated the behavior and found that if we input a string with Cyrillic letters only or a string with Cyrillic letters starting within the first 7 symbols of the string the encoding-decoding process does not cause any damage to the string. Hope it helps to reproduce the issue.

Thank you in advance.

**Comment by yas78** [comment]
@regdomain さん

私の環境で文字セットにUTF-8を設定してQRコードを作成したところ、iPhoneの標準カメラアプリやその他のアプリで正常にデコードすることができました。

[UTF-8]
ST00012|Name=ООО "Рога и копыта"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=АО "БАНК"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=Оплата заказа №123|Sum=100000

![utf8](https://user-images.githubusercontent.com/32599673/122795322-2afedc00-d2f8-11eb-9614-62227fafdce6.png)

あなたが使用しているQRコードリーダーがサポートしている文字セットはUTF-8で間違いありませんか？
UTF-8以外の別の文字セットとしてデコードしているのかもしれません。

バイトモードの文字セットはCreateSymbols関数のcharsetName引数で任意に設定することが可能です。
https://docs.cntd.ru/document/1200110981 によるとUTF-8以外にWindows-1251とKOI8-Rもサポートしているようなので
試しにそれらの文字セットで作成してみました。このQRコードが正常に読めるか確認してみてください。
また、過去にバイトモードでのエンコードが正常に行えないバグが存在した時期があるので、最新版を使用していない場合は最新のコミットで試してみてください。

[Windows-1251]
ST00011|Name=ООО "Рога и копыта"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=АО "БАНК"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=Оплата заказа №123|Sum=100000

![win1251](https://user-images.githubusercontent.com/32599673/122795377-394cf800-d2f8-11eb-9f66-c6b56b7dfafd.png)

[KOI8-R]
ST00013|Name=ООО "Рога и копыта"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=АО "БАНК"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=Оплата заказа №123|Sum=100000

![koi8-r](https://user-images.githubusercontent.com/32599673/122795391-3ce07f00-d2f8-11eb-96a8-ed0585345c63.png)

**Comment by regdomain** [comment]
Thank you for your reply. 

I can decode all your QR codes just fine with my Android scanner. But I cannot reproduce any of those. Below is my code snippet just as an example (I ported your library to Word):

`Set sbls = CreateSymbols()`
`sbls.AppendText "ST00011" & _`
`        "|Name=ООО ""Название компании""" & _`
`        "|PayeeINN=1234567890" & _`
`        "|KPP=123456789" & _`
`        "|PersonalAcc=40708407654768768769" & _`
`        "|BankName=АО ""Название банка""" & _`
`        "|BIC=123456789" & _`
`        "|CorrespAcc=30101810200000000000" & _`
`        "|Purpose=Оплата заказа №123" & _`
`        "|Sum=100000"`
`sbls(0).SaveAs ActiveDocument.Path & "\QRCode.svg", 2, , , fmtSVG`

As I understand, CreateSymbols() method supports 3 different charsets: "Shift_JIS" (default), "GB2312" and "EUC-KR":

`    Set sbls = CreateSymbols(charsetName:="Shift_JIS")`
`    Set sbls = CreateSymbols(charsetName:="GB2312")`
`    Set sbls = CreateSymbols(charsetName:="EUC-KR")`

I have tried all of them with no avail. Cyrillic symbols are just displayed incorrectly after decoding.

Interestingly when I change the "ST" field to "ST00011", "ST00012" or "ST00013" in .AppentText even without changing the charsetName argument in .CreateSymbols() the decoding pattern is also changed. I cannot understand why.

What am I doing wrong?

**Comment by yas78** [comment]
@regdomain さん

UTF-8の場合は以下のようにします。

`Set sbls = CreateSymbols(charsetName:="UTF-8")`

文字セットはShift_JIS、GB2312、EUC-KR以外にも設定可能です。
ADODB.Streamオブジェクトに依存しており、設定可能な文字セットはレジストリの[HKEY_CLASSES_ROOT\MIME\Database\Charset] で確認することができます。

https://docs.cntd.ru/document/1200110981 では、WIN1251なら"ST00011"、UTF8なら"ST00012"、KOI8Rなら”ST00013” と規定されているため、正しいコードは以下のようになります。（但し、KOI8-Rには"№"が存在しないため"?"になるかもしれません。）
また、Visual Basic EditorはUnicodeに対応していないため、ハードコーディングした文字列からは正しく作成できない可能性もあります。その場合はExcelのセルやWord文書中の文字列、またはテキストボックスをデータソースにしてみてください。

```
Sub WIN1251ver()
    Dim sbls As Symbols
    Set sbls = CreateSymbols(charsetName:="Windows-1251")
    sbls.AppendText "ST00011" & _
    "|Name=ООО ""Название компании""" & _
    "|PayeeINN=1234567890" & _
    "|KPP=123456789" & _
    "|PersonalAcc=40708407654768768769" & _
    "|BankName=АО ""Название банка""" & _
    "|BIC=123456789" & _
    "|CorrespAcc=30101810200000000000" & _
    "|Purpose=Оплата заказа №123" & _
    "|Sum=100000"
    sbls(0).SaveAs ActiveDocument.Path & "\QRCode.svg", 2, , , fmtSVG
End Sub

Sub UTF8ver()
    Dim sbls As Symbols
    Set sbls = CreateSymbols(charsetName:="UTF-8")
    sbls.AppendText "ST00012" & _
    "|Name=ООО ""Название компании""" & _
    "|PayeeINN=1234567890" & _
    "|KPP=123456789" & _
    "|PersonalAcc=40708407654768768769" & _
    "|BankName=АО ""Название банка""" & _
    "|BIC=123456789" & _
    "|CorrespAcc=30101810200000000000" & _
    "|Purpose=Оплата заказа №123" & _
    "|Sum=100000"
    sbls(0).SaveAs ActiveDocument.Path & "\QRCode.svg", 2, , , fmtSVG
End Sub

Sub KOI8Rver()
    Dim sbls As Symbols
    Set sbls = CreateSymbols(charsetName:="KOI8-R")
    sbls.AppendText "ST00013" & _
    "|Name=ООО ""Название компании""" & _
    "|PayeeINN=1234567890" & _
    "|KPP=123456789" & _
    "|PersonalAcc=40708407654768768769" & _
    "|BankName=АО ""Название банка""" & _
    "|BIC=123456789" & _
    "|CorrespAcc=30101810200000000000" & _
    "|Purpose=Оплата заказа №123" & _
    "|Sum=100000"
    sbls(0).SaveAs ActiveDocument.Path & "\QRCode.svg", 2, , , fmtSVG
End Sub
```

**Comment by regdomain** [comment]
Thank you for your hint. Now it's OK! 
I did not realize I could pass any character set supported by ADODB.Stream.
I was also confused why the default character set (Shift_JIS) worked just fine with a simple string containing Cyrillic symbols like: 

`   Set sbls = CreateSymbols()`
`    sbls.AppendText "Русский текст"`

but could not do the job with a more complex string discussed in the previous messages.

Could you please explain?

**Comment by yas78** [comment]
@regdomain さん

> I was also confused why the default character set (Shift_JIS) worked just fine with Cyrillic symbols:

私のQRコードリーダーではShift_JISもUTF-8 も同じ正常なデコード結果が得られたので私も混乱しました。
調査してみると理由は簡単で、キリル文字はShift_JISにも含まれているからです。
Shift_JISに含まれる文字の場合は'漢字モード'で圧縮してエンコードされます。
'漢字モード'をサポートしているQRコードリーダーであれば今回の結果になります。
![shiftjis_cyrillic](https://user-images.githubusercontent.com/32599673/122940166-3234f100-d3af-11eb-82ab-a7258107d8c9.PNG)

**Comment by regdomain** [comment]
I rephrased my question after you have replied, sorry.
I see Cyrillic letters are included in Shift_JIS character set, good to know. :-) But normal ASCII characters are also there. Why the default encoding did not work with a more complicated "payment statement" string then?

**Comment by yas78** [comment]
Google翻訳が分かりにくいのであなたの質問を正しく理解できているか分かりませんが、
例えば、デフォルトのShift_JISでエンコードした場合に何故下記の"Рога и копыта"が"�Q���s�p �y �{���������p"にデコードされたのかという疑問でしょうか？

> ST00012|Name=ООО "Рога и копыта"|PayeeINN=1234567890|KPP=123456789|PersonalAcc=40708407654768768769|BankName=АО "БАНК"|BIC=123456789|CorrespAcc=30101810200000000000|Purpose=Оплата заказа №123|Sum=100000

これはあくまで推測ですが、あなたが使用しているQRコードリーダー（下記の事象から推測すると、おそらく”ГОСТ Р 56042-2014”に対応したリーダー）に起因していると思います。
> Interestingly when I change the "ST" field to "ST00011", "ST00012" or "ST00013" in .AppentText even without changing the charsetName argument in .CreateSymbols() the decoding pattern is also changed. I cannot understand why.

"Рога и копыта"は、Shift_JISでエンコードすると以下のバイナリ列となります。
> 84 51 84 80 84 73 84 70 20 84 79 20 84 7B 84 80 84 81 84 8D 84 84 84 70

ここで、支払明細書文字列に"ST00012"が指定されているため、あなたのQRコードリーダーはShift_JISのバイナリ列をUTF-8としてデコードを試みます。
> 84 > �
> 51 > Q
> 84 > �
> 80 > �
> 84 > �
> 73 > s
> 84 > �
> 70 > p
> 20 > Space
> 84 > �
> 79 > y
> 20 > Space
> 84 > �
> 7B > {
> 84 > �
> 80 > �
> 84 > �
> 81 > �
> 84 > �
> 8D > �
> 84 > �
> 84 > �
> 84 > �
> 70 > p

”Name=ООО" の ”ООО” も同じ理由です。これはShift_JISに含まれている文字のため
> О=0x844F

> 84 > �
> 4F > O

にデコードされます。

**Comment by regdomain** [comment]
Thank you again for you patience and a nice piece of work your library is!
