### ISSUE TITLE
GetPictureのEMF対応

### ISSUE THREAD

**Issue by lunark** [yas78/QRCodeLibVBA#5]
難しいのを承知でリクエスト（というか可能なのかも含めてご確認）したいのですが、
EMF版のGetPictureの実装などは難しいでしょうか？

というのは、
```vb
    With Me.imgQr
        .PictureAlignment = fmPictureAlignmentCenter
        .PictureSizeMode = fmPictureSizeModeZoom
        .Picture = sbls(0).GetPicture(MODULE_SIZE)
    End With
```
というサンプルの方法を試してみたのですが、20mm角程度でVersion30以降などの細かいQRを
印字したいとき、現状の実装ですとアンチエイリアシングがうまく切れず、印字品質に優れません。
（アンチエイリアスによるつぶれが気になる）
検証環境：Microsoft Excel 2016

こちらで試したこととしては、GetMonochromeBMPの実装を参考に、
1bpp画像を送るGetPictureを試作もしてみたのですが、それでもアンチエイリアスが切れず、とい状況です。

宜しくお願い致します。

**Comment by yas78** [comment]
残念ながら私はEMFについて詳しくないので何とも答えられません。
「EMFからIPictureDispオブジェクトに変換」ということだと思いますが、これが印刷品質の改善に有効な手段なのか疑問です。元画像・画面・プリンタの解像度、ExcelやImageコントロールの動作との複合的な要因で発生しているのではないでしょうか。
そもそも20mm角でバージョン30以上ともなると、もはやQRコードであることも認識できない真っ黒な画像になりませんか？
おそらくアプローチの方向としては鮮明さを求めるのではなく、ぼやけても問題なく読み取れるように１シンボルのデータ量を抑える方が良いと思います。分割QRコードの作成機能は備えているのでこちらを活用してみてください。

参考までにお伝えしておくと、1モジュール幅の最小ピクセル数はSymbolクラスのMIN_MODULE_SIZE 定数で2に設定してありますが、実際はSVG形式を除き1でも動作します。予め画像サイズを小さくすれば縮小する必要がなくなり画像の劣化を抑えられるのではないでしょうか。

**Comment by yas78** [comment]
調べてみると思いの外簡単に実装できそうだったのでやってみました。
GetPictureメソッドの引数でBitmapとMetafileを選択できるようにしています。
ついでにEMF形式でファイル保存もできるようにしました。
これで実際に印刷時のつぶれが解消するのか確認してその結果をご報告ください。

以下はGetPictureとSaveAs の使い方です。
```
Dim sbls As Symbols
Set sbls = CreateSymbols()
sbls.AppendText "012345abcdefg"

Dim pict As stdole.IPictureDisp
' Bitmap
Set pict = sbls(0).GetPicture(picType:=Bitmap)
' Metafile
Set pict = sbls(0).GetPicture(picType:=EnhMetaFile)
' EMF
sbls(0).SaveAs "filename", fmt:=fmtEMF
```

**Comment by lunark** [comment]
ご対応感謝致します。動作ご確認させて頂きました。
印字品質についてですが、目論見通り成功しているものと思います。

やはりImageコントロール上にベクタ形式の画像を配すると、そのプリンタスプール時には
ラスタ化されずにデータが流れるようで、印字品質が極めて向上します。

Excelから出力したPDFにおいても以下の通り、ベクタ画像で貼り込まれているように
見えます。
https://www.dropbox.com/s/uth9ewkgv0tvvsh/WorksheetFunctionSample.pdf?dl=0
以上、ご報告になります。重ね重ねありがとう御座いました。

**Comment by yas78** [comment]
確認結果のご報告ありがとうございます。

期待通りの結果が得られたようで良かったです。
なるほど、Imageコントロールの画像はベクター形式のままプリンターまで届けることができるのですね。勉強になりました。
（詳しくはありませんが、PostScript対応プリンタかどうか、なども関係してくるのかもしれませんね。）

それでは何か不具合等ありましたらお知らせ下さい。
ありがとうございました。
